### ISSUE TITLE
1.0.4 causes parts of `assets/tests.js` not to be transpiled

### ISSUE THREAD

**Issue by YoranBrondsema** [sir-dunxalot/ember-cli-sass-lint#12]
In 1.0.4, all the `*.js` files in `app/` appear in `assets/tests.js` without transpilation. Reverting back to 1.0.3 fixes the issue, so maybe it's due to the changes in https://github.com/sir-dunxalot/ember-cli-sass-lint/commit/a433f934de876c8b155804a9d6a1adff7bfa36f9.

I think it's the same issue as https://github.com/ember-cli/ember-cli/issues/7063 (and fixed by https://github.com/billybonks/ember-cli-stylelint/pull/71/files for `ember-cli-stylelint`).

**Comment by RobbieTheWagner** [comment]
Would you be interested in throwing together a PR to fix this? 😄

**Comment by YoranBrondsema** [comment]
@rwwagner90 I'm not a Broccoli expert but I'll try!
