### ISSUE TITLE
sass-lint.yml instead of sass-lint's .sass-lint.yml

### ISSUE THREAD

**Issue by john-kurkowski** [sir-dunxalot/ember-cli-sass-lint#2]
From [the README](https://github.com/sir-dunxalot/ember-cli-sass-lint/blame/0.1.0/README.md#L16):

> Linting configuration can be added in a `sass-lint.yml` file as required by [Sass Lint](https://github.com/sasstools/sass-lint).

This is misleading. sass-lint defaults to [a _dotfile_ called .sass-lint.yml](https://github.com/sasstools/sass-lint/blame/v1.5.1/README.md#L13). So to be consistent with the upstream project, you have to specify configuration for this addon in ember-cli-build.js. Can it use the same default as sass-lint?

**Comment by sir-dunxalot** [comment]
Fix released in `1.0.0`.

**Comment by john-kurkowski** [comment]
Thanks!
