### ISSUE TITLE
The global `ok` is removed in QUnit 2.0

### ISSUE THREAD

**Issue by lancedikson** [sir-dunxalot/ember-cli-sass-lint#8]
The problem depends on `broccoli-sass-lint` issue: https://github.com/sir-dunxalot/broccoli-sass-lint/issues/9. Waiting for a patch release 🎉

**Comment by RobbieTheWagner** [comment]
@lancedikson thanks for bringing this to our attention and for the PR with the fix! I just released 1.1.2 of broccoli-sass-lint.

**Comment by RobbieTheWagner** [comment]
@lancedikson I just released version 1.0.3 of this addon, which points to the latest version of broccoli-sass-lint, and I also updated ember-cli and all other dependencies. Can you please install the new version of this addon and let me know if everything works correctly for you?

**Comment by lancedikson** [comment]
@rwwagner90, yes, it works now. Thanks a lot! 👍

**Comment by RobbieTheWagner** [comment]
No problem. Thanks for your help!
